### ISSUE TITLE
Repeated reload on login

### ISSUE THREAD

**Issue by cmei4444** [knative-portability/large-events#54]
After logging in at [the home page](https://pageserve-l3zyoxchqa-uc.a.run.app/v1/) (or any other page) the app reloads repeatedly. 

Looking at the logs, pageserve keeps getting POST calls to /v1/authenticate. I haven't been able to find what's been causing it. Could it be an issue with my browser, or something else? If it's a browser issue then we should handle it somehow or include instructions to avoid it.

**Comment by mukobi** [comment]
Fixed in #55
